# Generated by Django 4.2.30 on 2026-07-15 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(blank=True, max_length=2, verbose_name="UF"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "celular",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("site", models.URLField(blank=True, verbose_name="Website")),
                ("nome", models.CharField(max_length=255, verbose_name="Razão Social")),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome Fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Inscrição Estadual"
                    ),
                ),
                (
                    "inscricao_municipal",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Inscrição Municipal"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="empresas/logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "cor_primaria",
                    models.CharField(
                        default="#0d6efd", max_length=7, verbose_name="Cor Primária"
                    ),
                ),
                (
                    "cor_secundaria",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="Cor Secundária"
                    ),
                ),
                (
                    "limite_usuarios",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Limite de Usuários"
                    ),
                ),
                (
                    "data_expiracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Expiração"
                    ),
                ),
                (
                    "modulo_vendas",
                    models.BooleanField(default=True, verbose_name="Módulo Vendas"),
                ),
                (
                    "modulo_compras",
                    models.BooleanField(default=True, verbose_name="Módulo Compras"),
                ),
                (
                    "modulo_estoque",
                    models.BooleanField(default=True, verbose_name="Módulo Estoque"),
                ),
                (
                    "modulo_financeiro",
                    models.BooleanField(default=True, verbose_name="Módulo Financeiro"),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "permissions": [
                    ("gerenciar_empresa", "Pode gerenciar configurações da empresa")
                ],
            },
        ),
    ]
