# Generated by Django 6.0.7 on 2026-07-19 21:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="endereço de e-mail"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="nome completo"),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="usuarios/avatars/"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="superusuário"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="data de cadastro",
                    ),
                ),
                (
                    "ultimo_acesso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último acesso"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "pode_vender",
                    models.BooleanField(default=False, verbose_name="Pode Vender"),
                ),
                (
                    "pode_comprar",
                    models.BooleanField(default=False, verbose_name="Pode Comprar"),
                ),
                (
                    "pode_gerenciar_estoque",
                    models.BooleanField(
                        default=False, verbose_name="Pode Gerenciar Estoque"
                    ),
                ),
                (
                    "pode_ver_financeiro",
                    models.BooleanField(
                        default=False, verbose_name="Pode Ver Financeiro"
                    ),
                ),
                (
                    "pode_gerenciar_usuarios",
                    models.BooleanField(
                        default=False, verbose_name="Pode Gerenciar Usuários"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_empresa",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
                "permissions": [
                    ("acessar_dashboard", "Pode acessar o dashboard"),
                    (
                        "gerenciar_todas_empresas",
                        "Pode gerenciar todas as empresas (superadmin)",
                    ),
                ],
            },
        ),
    ]
