# Generated by Django 6.0.7 on 2026-07-19 21:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIAR", "Criar"),
                            ("ATUALIZAR", "Atualizar"),
                            ("DELETAR", "Deletar"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("EXPORTAR", "Exportar"),
                            ("IMPORTAR", "Importar"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("app_label", models.CharField(max_length=100, verbose_name="App")),
                ("model_name", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID do Objeto"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "dados_antes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados Antes"
                    ),
                ),
                (
                    "dados_depois",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados Depois"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-criado_em"],
            },
        ),
    ]
