# Generated by Django 4.2.30 on 2026-07-15 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIAR", "Criar"),
                            ("ATUALIZAR", "Atualizar"),
                            ("DELETAR", "Deletar"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("EXPORTAR", "Exportar"),
                            ("IMPORTAR", "Importar"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("app_label", models.CharField(max_length=100, verbose_name="App")),
                ("model_name", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID do Objeto"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "dados_antes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados Antes"
                    ),
                ),
                (
                    "dados_depois",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados Depois"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_auditoria",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "-criado_em"],
                        name="auditoria_l_empresa_56ac9c_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-criado_em"],
                        name="auditoria_l_usuario_453dac_idx",
                    ),
                    models.Index(
                        fields=["acao", "-criado_em"],
                        name="auditoria_l_acao_b3ad84_idx",
                    ),
                ],
            },
        ),
    ]
