# Generated by Django 6.0.7 on 2026-07-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auditoria", "0001_initial"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logauditoria",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs_auditoria",
                to="empresas.empresa",
            ),
        ),
    ]
